name: SHASUM summary for each changed release

on:
  pull_request:
    branches: [ "main" ]

jobs:
  comment-summary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show changed files
        run: git diff --no-commit-id --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      - name: run shasum-summary
        run: python3 contrib/shasum-summary/main.py ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > $GITHUB_STEP_SUMMARY
      - name: show summary
        run: cat $GITHUB_STEP_SUMMARY
