name: SHASUM summary for each changed release

on:
  pull_request:
    branches: [ "main" ]

jobs:
  SHASUMs-summary:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show changed files
        run: git diff --no-commit-id --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
      - name: run shasum-summary
        run: python3 contrib/shasum-summary/main.py ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} > summary
      - name: show summary
        run: cat summary
      - name: github job summary
        run: cat summary > $GITHUB_STEP_SUMMARY
      - name: Create status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "${{ github.event.workflow_run.conclusion }}",
            "context": "SHASUM summary",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail
